version: '3.1'

services:
  db: 
    image: redis:7-alpine3.18
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - /db_redis_data:/data
